In [1]:
import warnings
#warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import os
import create_aggregate_df as agg_df

%matplotlib inline
pd.set_option('display.max_columns', None);

In [2]:
path = "../data/2015_loan_data/";
loans_2015_all = agg_df.create_aggregate_df(path);
loans_2015_all.head()

LoanStats_2015_B.csv

/Users/bhavenpatel/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2903: DtypeWarning: Columns (19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

LoanStats_2015_C.csv

/Users/bhavenpatel/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2903: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

LoanStats_2015_D.csv
LoanStats_2015_E.csv
LoanStats_2015_F.csv
LoanStats_2015_G.csv
LoanStats_2015_H.csv

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,20000,20000,20000.0,36 months,6.49%,612.89,A,A2,"TEAM LEAD, QUALITY ENGINEER",6 years,MORTGAGE,55000.0,Not Verified,Dec-2015,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,381xx,TN,29.15,0,Sep-1994,0,74.0,NaN,9,0,4851,23.8%,23,w,1818.92,1818.92,20207.340000,20207.34,18181.08,2026.26,0.0,0.0,0.0,Oct-2018,612.89,Oct-2018,Oct-2018,0,NaN,1,Individual,NaN,NaN,NaN,0,0,205155,1.0,3.0,1.0,4.0,3.0,36812.0,79.0,1.0,1.0,2776.0,62.0,20400,1.0,0.0,3.0,5,25644,9924.0,21.9,0,0,87.0,255,8,3,1,8.0,NaN,3.0,NaN,0,1,3,2,9,8,5,14.0,3,9,0.0,0,0,2,95.7,0.0,0,0,247433,41663,12700,46367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,10000,10000,10000.0,36 months,12.88%,336.37,C,C2,Contract Specialist,4 years,MORTGAGE,91392.0,Not Verified,Dec-2015,Fully Paid,n,NaN,NaN,house,Home buying,644xx,MO,9.44,0,Sep-2006,0,NaN,NaN,13,0,6959,41.7%,33,f,0.00,0.00,11316.890190,11316.89,10000.00,1316.89,0.0,0.0,0.0,Mar-2017,6961.97,NaN,Aug-2018,0,NaN,1,Individual,NaN,NaN,NaN,0,0,304514,2.0,4.0,1.0,4.0,6.0,66773.0,88.0,1.0,1.0,2180.0,71.0,16700,0.0,0.0,3.0,7,23424,433.0,90.2,0,0,104.0,111,9,6,3,9.0,NaN,8.0,NaN,0,3,5,3,6,19,7,11.0,5,13,0.0,0,0,3,100.0,100.0,0,0,321380,73732,4400,68648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,18000,18000,18000.0,36 months,7.49%,559.83,A,A4,Systems Support Engineer,5 years,MORTGAGE,75000.0,Not Verified,Dec-2015,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,030xx,NH,25.65,0,Mar-2001,1,46.0,NaN,12,0,7758,33.2%,47,w,0.00,0.00,19771.097253,19771.10,18000.00,1771.10,0.0,0.0,0.0,Oct-2017,8073.57,NaN,Oct-2018,0,NaN,1,Individual,NaN,NaN,NaN,0,0,304914,3.0,6.0,2.0,3.0,6.0,94902.0,76.0,2.0,3.0,4829.0,65.0,23400,1.0,3.0,3.0,7,25410,12642.0,38.0,0,0,177.0,175,6,6,1,6.0,46.0,6.0,46.0,0,2,2,4,15,24,5,21.0,2,12,0.0,0,0,5,97.8,50.0,0,0,335119,102660,20400,107522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,20000,20000,20000.0,36 months,5.32%,602.30,A,A1,driver,9 years,OWN,65000.0,Not Verified,Dec-2015,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,125xx,NY,18.83,0,May-1991,1,NaN,NaN,12,0,2269,3%,17,w,0.00,0.00,21631.724329,21631.72,20000.00,1631.72,0.0,0.0,0.0,Aug-2018,3577.50,NaN,Aug-2018,0,NaN,1,Individual,NaN,NaN,NaN,0,0,15444,0.0,2.0,0.0,1.0,15.0,13175.0,44.0,0.0,1.0,1448.0,15.0,76200,2.0,0.0,1.0,2,1287,73931.0,3.0,0,0,63.0,295,19,15,0,19.0,NaN,4.0,NaN,0,3,3,10,11,4,10,13.0,3,12,0.0,0,0,0,100.0,0.0,0,0,106217,15444,76200,30017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,16000,16000,16000.0,60 months,12.88%,363.07,C,C2,Unix System Administrator,10+ years,OWN,90000.0,Not Verified,Dec-2015,Current,n,NaN,NaN,home_improvement,Home improvement,064xx,CT,6.39,0,Jan-1996,0,26.0,NaN,8,0,11594,43.9%,17,w,8470.97,8470.97,11952.690000,11952.69,7529.03,4423.66,0.0,0.0,0.0,Oct-2018,363.07,Oct-2018,Oct-2018,0,NaN,1,Individual,NaN,NaN,NaN,0,0,224292,0.0,0.0,0.0,0.0,79.0,0.0,NaN,1.0,3.0,3955.0,44.0,26400,0.0,0.0,0.0,3,28037,6087.0,62.7,0,0,239.0,115,7,7,5,7.0,26.0,NaN,26.0,0,4,5,4,4,4,7,8.0,5,8,0.0,0,0,1,86.7,25.0,0,0,263351,11594,16300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
loans_2015_all.shape

(421095, 145)

In [4]:
loans_2015_all = loans_2015_all.loc[loans_2015_all.loan_status != 'Current', :];
loans_2015_all.shape

(346828, 145)

In [5]:
print(loans_2015_all.policy_code.unique())

[1]

In [7]:
#make category for whether the loan defaulted
loans_2015_all['default'] = 1;
loans_2015_all.loc[loans_2015_all.loan_status == 'Fully Paid', 'default'] = 0;

In [8]:
#calculate the def
ratio = loans_2015_all.default.sum() / loans_2015_all.default.count()
print('Default Percentage = {0}'.format(ratio))

Default Percentage = 0.22238400590494423